function setCookie(e,t,o){const n=new Date;n.setTime(n.getTime()+24*o*60*60*1e3);o="expires="+n.toUTCString();document.cookie=e+"="+t+";"+o+";path=/"}function getCookie(e){var o=e+"=";let t=decodeURIComponent(document.cookie);var n=t.split(";");for(let t=0;t<n.length;t++){let e=n[t];for(;" "==e.charAt(0);)e=e.substring(1);if(0==e.indexOf(o))return e.substring(o.length,e.length)}return""}function darkmode(){setCookie("isdark","true",365);const e=document.getElementById("lightfood"),t=document.getElementById("darkfood");null!=t&&(t.classList.remove("hidden"),t.style.animation="landing ease 1s",e.classList.add("hidden"),e.style.animation="landing ease 1s"),document.body.classList.add("dark"),document.body.classList.add("colortransition")}function lightmode(){const e=document.getElementById("lightfood"),t=document.getElementById("darkfood");null!=t&&(t.classList.add("hidden"),e.classList.remove("hidden")),setCookie("isdark","false",365),document.body.classList.remove("dark")}function checkCookie(){const e=document.getElementById("colormode");var t=getCookie("isdark");if("true"==t){darkmode();try{e.checked=!0}catch(e){}}else{try{e.checked=!1}catch(e){}""!=t&&null!=t||setCookie("isdark","false",365)}}function getbold(){for(var e=document.getElementsByClassName("detaillangkah"),t=0;t<e.length;t++){var o=e[t].innerHTML.match(/\d+/g);if(null!=o)for(var n=0;n<o.length;n++){var s=document.createElement("b");s.innerHTML=o[n],e[t].innerHTML=e[t].innerHTML.replace(o[n],s.outerHTML)}}}window.addEventListener("scroll",e=>{const t=document.getElementById("navbarwrapper");50<window.pageYOffset?t.classList.add("add-shadow"):t.classList.remove("add-shadow")}),window.onload=()=>{
    try {
        let inputQuery = document.getElementById("inputQuery").value;
        if (inputQuery != "") {
            var input = document.getElementById("inputQuery").focus();
        }
    } catch (error) {
        console.log(error);
    }
    
     

    
    
    
    ;getbold(),checkCookie();try{getCookie("isdark");const e=document.getElementById("colormode");e.addEventListener("click",()=>{(e.checked?darkmode:lightmode)()})}catch(e){}document.getElementById("user").onclick=()=>{let e=document.getElementsByClassName("user-dropdown")[0];e.classList.toggle("show")},document.addEventListener("click",e=>{var t=document.getElementById("user");const o=document.getElementsByClassName("user-dropdown")[0];let n=e.target;do{if(n==o)return;if(n==t)return}while(n=n.parentNode);o.classList.remove("show")}),document.querySelectorAll(".loginnavbar").forEach(e=>{e.onclick=()=>{const e=document.getElementsByClassName("user-dropdown")[0];e.classList.remove("show");let t=document.getElementsByClassName("modalwrapper")[0];t.style.display="flex",document.body.classList.add("remove-scrolling")}}),window.onclick=e=>{var t=document.getElementsByClassName("exitbutton")[0];let o=document.getElementsByClassName("modalwrapper")[0];var n=document.getElementsByClassName("exitbutton")[0].getElementsByTagName("svg")[0].children[0],s=document.getElementsByClassName("exitbutton")[0].getElementsByTagName("svg")[0];return e.target==document.getElementsByClassName("modalwrapper")[0]||e.target==t||e.target==n?(o.style.display="none",void document.body.classList.remove("remove-scrolling")):void(e.target==s&&(o.style.display="none",document.body.classList.remove("remove-scrolling")))}};